---
sidebar: sidebar 
permalink: task_adding_ontap_cloud.html 
keywords: discover, discovering, add, adding, existing 
summary: Vous pouvez découvrir et ajouter des systèmes Cloud Volumes ONTAP existants à Cloud Manager. Cette opération peut être possible si vous avez déployé un nouveau système Cloud Manager. 
---
= Ajout de systèmes Cloud Volumes ONTAP existants à Cloud Manager
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez découvrir et ajouter des systèmes Cloud Volumes ONTAP existants à Cloud Manager. Cette opération peut être possible si vous avez déployé un nouveau système Cloud Manager.

.Avant de commencer
Vous devez connaître le mot de passe du compte d'administrateur Cloud Volumes ONTAP.

.Étapes
. Sur la page environnements de travail, cliquez sur *découvrir* et sélectionnez *Cloud Volumes ONTAP*.
. Sélectionnez le fournisseur de cloud dans lequel réside le système.
. Sur la page Région, choisissez la région dans laquelle les instances sont exécutées, puis sélectionnez les instances.
. Sur la page informations d'identification, entrez le mot de passe de l'utilisateur administrateur Cloud Volumes ONTAP, puis cliquez sur *Go*.


.Résultat
Cloud Manager ajoute les instances Cloud Volumes ONTAP à l'espace de travail.
