---
sidebar: sidebar 
permalink: task_enabling_flash_cache.html 
keywords: cloud volumes ontap, aws, ec2, flash cache, read-intensive, read, random, databases, email, file services, c5d.4xlarge, c5d.9xlarge, r5d.2xlarge, compression, performance, azure, nvme, standard, l8s, vm type, virtual machine 
summary: Certaines configurations Cloud Volumes ONTAP dans AWS et Azure incluent le stockage NVMe local, qui utilise Cloud Volumes ONTAP comme Flash cache pour de meilleures performances. 
---
= Activation de Flash cache sur Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Certaines configurations Cloud Volumes ONTAP dans AWS et Azure incluent le stockage NVMe local, qui utilise Cloud Volumes ONTAP comme _Flash cache_ pour de meilleures performances.



== Qu'est-ce que Flash cache ?

Flash cache accélère l'accès aux données grâce à la mise en cache intelligente en temps réel des données utilisateur et des métadonnées NetApp lues récemment. Il est efficace pour les charges de travail exigeant une capacité de lecture aléatoire maximale, dont les bases de données, la messagerie et les services de fichiers.



== Limites

* La compression doit être désactivée sur tous les volumes pour tirer parti des améliorations des performances de Flash cache.
* La réactivation du cache après un redémarrage n'est pas prise en charge avec Cloud Volumes ONTAP.




== Activation de Flash cache sur Cloud Volumes ONTAP dans AWS

Flash cache est pris en charge avec Cloud Volumes ONTAP Premium et BYOL dans AWS.

.Étapes
. Sélectionnez l'un des types d'instances EC2 suivants avec un système Cloud Volumes ONTAP Premium ou BYOL existant :
+
** c5d.4xlarge
** c5d.9xlarge
** r5d.2xlarge


. Désactivez la compression sur tous les volumes pour bénéficier des améliorations des performances de Flash cache.
+
Sélectionnez l'efficacité du stockage lors de la création d'un volume depuis Cloud Manager, ou créez un volume, puis http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-8508A4CB-DB43-4D0D-97EB-859F58B29054.html["Désactiver la compression des données à l'aide de l'interface de ligne de commande"^].





== Activation de Flash cache sur Cloud Volumes ONTAP dans Azure

Flash cache est pris en charge avec Cloud Volumes ONTAP (BYOL) sur les systèmes à un nœud.

.Étapes
. Sélectionnez le type de machine virtuelle Standard_L8S_v2 avec un système Cloud Volumes ONTAP BYOL à un seul nœud dans Azure.
. Désactivez la compression sur tous les volumes pour bénéficier des améliorations des performances de Flash cache.
+
Sélectionnez l'efficacité du stockage lors de la création d'un volume depuis Cloud Manager, ou créez un volume, puis http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-8508A4CB-DB43-4D0D-97EB-859F58B29054.html["Désactiver la compression des données à l'aide de l'interface de ligne de commande"^].


