---
pagenav: false 
sidebar: sidebar 
permalink: task_getting_started_azure.html 
keywords: microsoft, azure, netapp, data fabric, hybrid cloud, cloud, public cloud, networking, marketplace, virtual machine, vnet, quick, getting started, install, installing, deploy, deploying, setup, setting up, launching, requirements, prerequisites, cloud central, permissions, custom role, role, json, permissions, virtual machine, video, connectivity, internet, outbound, endpoint, connection, networks, vpn, replicating, policy, iam, setupasservice, sign up, cloud manager, cloud volumes ontap, cloud ontap, subscription, create 
summary: Vous pouvez commencer avec Cloud Volumes ONTAP à Azure en suivant quelques étapes rapides. 
---
= Mise en route de Cloud Volumes ONTAP dans Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lancez-vous avec Cloud Volumes ONTAP en configurant Azure, puis en déployant le logiciel Cloud Manager depuis NetApp Cloud Central. Des instructions distinctes sont disponibles pour déployer Cloud Manager dans le link:task_installing_azure_gov.html["Les régions du gouvernement des États-Unis Azure"] et po link:task_installing_azure_germany.html["Les régions Azure Germany"].



=== Configurez votre réseau

[role="quick-margin-para"]
Activez l'accès Internet sortant à partir du VNet cible pour que Cloud Manager et Cloud Volumes ONTAP puissent contacter plusieurs terminaux.

[role="quick-margin-para"]
Cette étape est importante car Cloud Manager ne peut pas déployer Cloud Volumes ONTAP sans accès Internet sortant. Si vous devez limiter la connectivité sortante, reportez-vous à la liste des noeuds finaux pour link:reference_networking_cloud_manager.html#outbound-internet-access["Le gestionnaire Cloud"] et link:reference_networking_azure.html["Cloud Volumes ONTAP"].



=== Fournissez les autorisations Azure requises

[role="quick-margin-para"]
Lorsque vous déployez Cloud Manager à partir de NetApp Cloud Central, vous devez utiliser un compte Azure disposant des autorisations nécessaires pour déployer la machine virtuelle Cloud Manager.

. Téléchargez le https://mysupport.netapp.com/cloudontap/iampolicies["Politique NetApp Cloud Central pour Azure"^].
. Modifiez le fichier JSON en ajoutant votre ID d'abonnement Azure au champ " AssignableScopes ".
. Utilisez le fichier JSON pour créer un rôle personnalisé dans Azure nommé _Azure SetupAsService_.
+
Exemple : *az role definition create --role-definition C:\Policy_for_Setup_as_Service_Azure.json*

. À partir du portail Azure, attribuez le rôle personnalisé à l'utilisateur qui déploiera Cloud Manager à partir de Cloud Central.




=== Lancez Cloud Manager à partir de NetApp Cloud Central

[role="quick-margin-para"]
Le logiciel Cloud Manager est requis pour déployer et gérer Cloud Volumes ONTAP. Quelques minutes suffisent pour lancer une instance Cloud Manager à partir de https://cloud.netapp.com["Cloud Central"^].



=== Lancez Cloud Volumes ONTAP à l'aide de Cloud Manager

[role="quick-margin-para"]
Une fois Cloud Manager prêt, cliquez simplement sur Créer, sélectionnez le type de système que vous souhaitez déployer et suivez les étapes de l'assistant. Après 25 minutes, votre premier système Cloud Volumes ONTAP doit être opérationnel.

.Liens connexes
* link:concept_evaluating.html["L'évaluation"]
* link:reference_networking_cloud_manager.html["Configuration réseau requise pour Cloud Manager"]
* link:reference_networking_azure.html["Configuration réseau requise pour Cloud Volumes ONTAP dans Azure"]
* link:reference_security_groups_azure.html["Règles de groupe de sécurité pour Azure"]
* link:task_adding_azure_accounts.html["Ajout de comptes Azure à Cloud Manager"]
* link:reference_permissions.html#what-cloud-manager-does-with-azure-permissions["Ce que fait Cloud Manager avec les autorisations Azure"]
* link:task_deploying_otc_azure.html["Lancement d'Cloud Volumes ONTAP dans Azure"]
* link:task_launching_azure_mktp.html["Lancement de Cloud Manager à partir d'Azure Marketplace"]

